# Expose Prometheus via Kubernetes Service
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: prod   # 
spec:
  selector:
    app.kubernetes.io/name: prometheus
  ports:
    - port: 80
      targetPort: 9090
  type: ClusterIP
