---
# This Argo CD app installs the AWS Load Balancer Controller from the official Helm chart.
# Make sure the IAM role aws-load-balancer-controller is pre-provisioned via Terraform and linked to the correct Kubernetes service account.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: 1.7.1
    helm:
      parameters:
        - name: clusterName
          value: ce-grp-1-eks
        - name: serviceAccount.create
          value: "false"
        - name: serviceAccount.name
          value: aws-load-balancer-controller
        - name: region
          value: us-east-1
        - name: vpcId
          value: vpc-0ce13075f23d1c50d
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
