---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-prod
  namespace: argocd
  labels:   # add labels and below line
    app.kubernetes.io/part-of: ce-grp-1
spec:
  project: default
  source:
    repoURL: https://github.com/aalimsee/ce-grp-1-apps.git   # `repoURL` is correct and publicly/privately accessible
    targetRevision: HEAD                                     # `targetRevision` is valid (e.g., `HEAD`, `main`, `v1.0.0`)
    path: nginx-prod                                         # `path` points to a directory with `kustomization.yaml`
  destination:                                               # `destination.namespace` exists and is accessible
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:   # `syncPolicy.automated.prune` and `selfHeal` set if auto-sync is enabled
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
