# cluster-admins is bound to the actual cluster-admin ClusterRole. This is often done via:

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admins-binding
  namespace: argocd
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: cluster-admins   # same name as that found in terraform
  apiGroup: rbac.authorization.k8s.io
