---
# This is the root Application Argo CD watches. It syncs all child apps under argo-apps/

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: prod
spec:
  project: prod-test-ALB-controller
  source:
    repoURL: https://github.com/aalimsee/ce-grp-1-apps.git
    targetRevision: HEAD
    path: argo-apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
