---
# This is the root Application Argo CD watches. It syncs all child apps under argo-apps/
# This points to the apps/ folder in your repo, which contains the other Application definitions (like nginx-app.yaml and aws-load-balancer-controller-app.yaml).

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aalimsee/ce-grp-1-apps.git
    targetRevision: HEAD
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

# Create an Argo CD App to Manage RBAC
# In your app-of-apps.yaml, add a child application pointing to the RBAC directory
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-admins-rbac
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aalimsee/ce-grp-1-apps.git
    targetRevision: HEAD
    path: rbac
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system  # Or any appropriate namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
