---
# This tells Argo CD:
# Install the Helm chart under aws-load-balancer-controller/
# Use the values.yaml
# Deploy into the kube-system namespace
# Do not create the namespace

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://aws.github.io/eks-charts
    targetRevision: 1.7.1
    helm:
      values: |
        clusterName: ce-grp-1-eks
        region: us-east-1
        vpcId: vpc-0ce13075f23d1c50d
        serviceAccount:
          create: false
          name: aws-load-balancer-controller
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
