apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: test-grp-1-nginx-hc
 finalizers:
 - resources-finalizer.argocd.argoproj.io
spec:
 project: default
 sources:
 - repoURL: registry-1.docker.io/bitnamicharts
   chart: nginx
   targetRevision: 19.0.2
   helm:
     releaseName: test-grp-1-nginx-hc 
     valueFiles:
     - $values/test-grp-1-nginx-hc/values.yaml
 - repoURL: https://github.com/aalimsee/ce-grp-1-apps.git
   targetRevision: HEAD
   ref: values
 destination:
   namespace: test
   server: "https://kubernetes.default.svc"
 syncPolicy:
   syncOptions:
   - CreateNamespace=true
   automated:
     prune: true
     selfHeal: true

