---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-test-webapp-clifford
  namespace: argocd
  labels:   # add labels and below line
    app.kubernetes.io/part-of: ce-grp-1
spec:
  project: default
  source:
    repoURL: https://github.com/aalimsee/ce-grp-1-apps.git
    targetRevision: HEAD
    path: nginx-clifford
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
